matrix:
  platform:
  - linux/amd64
  - linux/arm64

labels:
  type: exec
  platform: ${platform}

steps:
- name: publish-linux
  image: bash
  commands:
  - podman run --rm -v $(pwd):/workspace -w /workspace registry.drycc.cc/drycc/go-dev make build
  - $(pwd)/_scripts/push_release.sh
  - rm -rf bin
  secrets:
  - github_token
  when:
    event:
    - tag

depends_on:
- test-linux